configMap:
  apiVersion: v1
  kind: ConfigMap
  metadata:
    name: gloriglobalsukses-backend
  data:
    "TZ": "Asia/Jakarta"
    "NODE_ENV": "production"
    "PORT": "3000"
service:
  kind: Service
  apiVersion: v1
  metadata:
    name: gloriglobalsukses-backend
  spec:
    selector:
      app: gloriglobalsukses-backend
    ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      name: http-gloriglobalsukses-backend
    type: NodePort
deployment:
  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: gloriglobalsukses-backend
    labels:
      app: gloriglobalsukses-backend
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: gloriglobalsukses-backend
    template:
      metadata:
        labels:
          app: gloriglobalsukses-backend
      spec:
        containers:
        - name: gloriglobalsukses-backend
          image: '{DOCKER_IMAGE_URI}'
          env:
            - name: TZ
              valueFrom:
                configMapKeyRef:
                  name: gloriglobalsukses-backend
                  key: TZ
            - name: NODE_ENV
              valueFrom:
                configMapKeyRef:
                  name: gloriglobalsukses-backend
                  key: NODE_ENV
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: gloriglobalsukses-backend
                  key: PORT
            - name: MONGODB_URL
              valueFrom:
                secretKeyRef:
                  name: gloriglobalsukses-backend-mongodb
                  key: url
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: gloriglobalsukses-backend-jwt
                  key: secret
            - name: JWT_ACCESS_EXPIRATION_MINUTES
              valueFrom:
                secretKeyRef:
                  name: gloriglobalsukses-backend-jwt
                  key: access_expiration_minutes
            - name: JWT_REFRESH_EXPIRATION_DAYS
              valueFrom:
                secretKeyRef:
                  name: gloriglobalsukses-backend-jwt
                  key: refresh_expiration_days
            - name: JWT_RESET_PASSWORD_EXPIRATION_MINUTES
              valueFrom:
                secretKeyRef:
                  name: gloriglobalsukses-backend-jwt
                  key: reset_password_expiration_minutes
            - name: JWT_VERIFY_EMAIL_EXPIRATION_MINUTES
              valueFrom:
                secretKeyRef:
                  name: gloriglobalsukses-backend-jwt
                  key: verify_email_expiration_minutes

            - name: SMTP_HOST
              valueFrom:
                secretKeyRef:
                  name: gloriglobalsukses-backend-smtp
                  key: host
            - name: SMTP_PORT
              valueFrom:
                secretKeyRef:
                  name: gloriglobalsukses-backend-smtp
                  key: port
            - name: SMTP_USERNAME
              valueFrom:
                secretKeyRef:
                  name: gloriglobalsukses-backend-smtp
                  key: username
            - name: SMTP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: gloriglobalsukses-backend-smtp
                  key: password
            - name: EMAIL_FROM
              valueFrom:
                secretKeyRef:
                  name: gloriglobalsukses-backend-smtp
                  key: from
          resources:
            limits:
              memory: "1024Mi"
              cpu: "500m"
        imagePullSecrets:
        - name: regcred
